SCREEN_WIDTH = 480
SCREEN_HEIGHT = 960
TILE_WIDTH = SCREEN_WIDTH // 4
TILE_HEIGHT = TILE_WIDTH // 2
HIT_POS = SCREEN_HEIGHT - TILE_HEIGHT * 2
COLUMNS = (0, 0 + TILE_WIDTH, 0 + TILE_WIDTH * 2, 0 + TILE_WIDTH * 3)